/*
 * main.c
 */

#include <stdbool.h>
#include <stdint.h>

#include <pru_rpmsg.h>
#include <pru_virtio_config.h>

#include <am18xx/pru_ctrl.h>
#include <am18xx/pru_intc.h>
#include <am18xx/sys_gpio.h>
#include <am18xx/sys_timer.h>


int main(void) {
	asm (
			"SUART_EMULATION:                                                    \n"
			"    XOR      r20, r20, r20                                          \n"
			"tx_asp_init1:                                                       \n"
			"    LBCO     &r22, C25, 0xA0, 4                                     \n"
			"    SET      r22, r22, 9                                            \n"
			"    SBCO     &r22, C25, 0xA0, 4                                     \n"
			"tx_asp_init2:                                                       \n"
			"    LBCO     &r22, C25, 0xA0, 4                                     \n"
			"    QBBC     tx_asp_init2, r22, 9                                   \n"
			"    SET      r22, r22, 8                                            \n"
			"    SBCO     &r22, C25, 0xA0, 4                                     \n"
			"tx_asp_init3:                                                       \n"
			"    LBCO     &r22, C25, 0xA0, 4                                     \n"
			"    QBBC     tx_asp_init3, r22, 8                                   \n"
			"    LDI      r23.w0, 0xffff & 0xFFFF                                \n"
			"    LDI      r23.w2, 0xffff >> 16                                   \n"
			"    SBCO     &r23, C25, 0xc0, 2                                     \n"
			"    SET      r22, r22, 10                                           \n"
			"    SBCO     &r22, C25, 0xA0, 4                                     \n"
			"tx_asp_init4:                                                       \n"
			"    LBCO     &r22, C25, 0xA0, 4                                     \n"
			"    QBBC     tx_asp_init4, r22, 10                                  \n"
			"    SET      r22, r22, 11                                           \n"
			"    SBCO     &r22, C25, 0xA0, 4                                     \n"
			"tx_asp_init5:                                                       \n"
			"    LBCO     &r22, C25, 0xA0, 4                                     \n"
			"    QBBC     tx_asp_init5, r22, 11                                  \n"
			"    SET      r22, r22, 12                                           \n"
			"    SBCO     &r22, C25, 0xA0, 4                                     \n"
			"tx_asp_init6:                                                       \n"
			"    LBCO     &r22, C25, 0xA0, 4                                     \n"
			"    QBBC     tx_asp_init6, r22, 12                                  \n"
			"rx_asp_init1:                                                       \n"
			"    LBCO     &r22, C25, 0x60, 4                                     \n"
			"    SET      r22, r22, 1                                            \n"
			"    SBCO     &r22, C25, 0x60, 4                                     \n"
			"rx_asp_init2:                                                       \n"
			"    LBCO     &r22, C25, 0x60, 4                                     \n"
			"    QBBC     rx_asp_init2, r22, 1                                   \n"
			"    SET      r22, r22, 0                                            \n"
			"    SBCO     &r22, C25, 0x60, 4                                     \n"
			"rx_asp_init3:                                                       \n"
			"    LBCO     &r22, C25, 0x60, 4                                     \n"
			"    QBBC     rx_asp_init3, r22, 0                                   \n"
			"    LDI      r23, 0xffff                                            \n"
			"    SBCO     &r23, C25, 0x80, 2                                     \n"
			"    SET      r22, r22, 2                                            \n"
			"    SBCO     &r22, C25, 0x60, 4                                     \n"
			"rx_asp_init4:                                                       \n"
			"    LBCO     &r22, C25, 0x60, 4                                     \n"
			"    QBBC     rx_asp_init4, r22, 2                                   \n"
			"    SET      r22, r22, 3                                            \n"
			"    SBCO     &r22, C25, 0x60, 4                                     \n"
			"rx_asp_init5:                                                       \n"
			"    LBCO     &r22, C25, 0x60, 4                                     \n"
			"    QBBC     rx_asp_init5, r22, 3                                   \n"
			"    SET      r22, r22, 4                                            \n"
			"    SBCO     &r22, C25, 0x60, 4                                     \n"
			"rx_asp_init6:                                                       \n"
			"    LBCO     &r22, C25, 0x60, 4                                     \n"
			"    QBBC     rx_asp_init6, r22, 4                                   \n"
			"LOCAL_INIT:                                                         \n"
			"    LBBO     &r23, r20, 0x084, 4                                    \n"
			"    MOV      R3.b0, r23.b0                                          \n"
			"    MOV      R3.b1, r23.b1                                          \n"
			"    MOV      R3.b2, r23.b2                                          \n"
			"    LDI      r23, 0xffff                                            \n"
			"    SBCO     &r23, C25, 0x80, 4                                     \n"
			"    LDI      r23, 0xffff                                            \n"
			"    SBCO     &r23, C25, 0xc0, 4                                     \n"
			"    QBEQ     CORE_LOOP, R3.b1, 0x1                                  \n"
			"    LDI      r23, 0xFF                                              \n"
			"    XOR      r24, r24, r24                                          \n"
			"    QBEQ     PRUxxxx_MODE_RX_ONLY, R3.b1, 0x2                       \n"
			"    LDI      r22, 0x0C0                                             \n"
			"    LDI      r25, 0x50                                              \n"
			"    LDI      r24, 0x1B0                                             \n"
			"    JMP      INIT_SAMPLE_PNT                                        \n"
			"PRUxxxx_MODE_RX_ONLY:                                               \n"
			"    LDI      r22, 0x90                                              \n"
			"    LDI      r25, 0x20                                              \n"
			"    LDI      r24, 0x170                                             \n"
			"INIT_SAMPLE_PNT:                                                    \n"
			"    SBBO     &r23, r22, 22, 1                                       \n"
			"    SBBO     &r20.b0, r22, 23, 1                                    \n"
			"    ADD      r22, r22, r25                                          \n"
			"    QBGE     INIT_SAMPLE_PNT, r22, r24                              \n"
			"    JMP      CORE_LOOP                                              \n"
			"TxServiceRequestHndlr:                                              \n"
			"    LBBO     &R2.w2, r20, 0x082, 2                                  \n"
			"    CLR      R2.w2, R2.w2, R10.b2                                   \n"
			"    SBBO     &R2.w2, r20, 0x082, 2                                  \n"
			"    CLR      R4.w0, R4.w0, 0x2                                      \n"
			"    SBBO     &R4.w0, R8, 0,  2                                      \n"
			"    SET      R5.b2, R5.b2, 0                                        \n"
			"    SBBO     &R5.b2, R8, 6,  1                                      \n"
			"    SET      R5.b3, R5.b3, 7                                        \n"
			"    SBBO     &R5.b3, R8, 7,  1                                      \n"
			"    XOR      R7.b0, R7.b0, R7.b0                                    \n"
			"    SBBO     &R7.b0, R8, 12,  1                                     \n"
			"    JMP      LOAD_TX_COMMON_INFO                                    \n"
			"ENABLE_TX_SERIALIZER:                                               \n"
			"    LBCO     &r23, C25, 0x10, 4                                     \n"
			"    AND      r22, R4.b1, 0x0F                                       \n"
			"    CLR      r23, r23, r22                                          \n"
			"    SBCO     &r23, C25, 0x10, 4                                     \n"
			"CLEAR_XSTAT:                                                        \n"
			"    LDI      r22, 0xFFFF                                            \n"
			"    SBCO     &r22, C25, 0xc0, 4                                     \n"
			"    JMP      MCASP_EVENT                                            \n"
			"TxServiceReqHndlLoop:                                               \n"
			"    JAL      r30.w0, READ_TX_DATA                                   \n"
			"    XOR      r28.w0, r28.w0, r28.w0                                 \n"
			"    LDI      r22, 0x03FF                                            \n"
			"    AND      r22, r22, R4.w2                                        \n"
			"    QBEQ     PRE_SCALAR1, r22, 0x1                                  \n"
			"    QBEQ     PRE_SCALAR2, r22, 0x2                                  \n"
			"    QBEQ     PRE_SCALAR4, r22, 0x4                                  \n"
			"    QBEQ     PRE_SCALAR6, r22, 0x6                                  \n"
			"    QBEQ     PRE_SCALAR12, r22, 0xC                                 \n"
			"    QBEQ     PRE_SCALAR16, r22, 0x10                                \n"
			"    QBLE     PRE_SCALAR24, r22, 0x18                                \n"
			"PRE_SCALAR1:                                                        \n"
			"    MOV      r28.w0, r24                                            \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    ADD      R7.b0, R7.b0, 1                                        \n"
			"    SBBO     &R7.b0, R8, 12,  1                                     \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"PRE_SCALAR2:                                                        \n"
			"    MOV      r22, R7.b1                                             \n"
			"    QBGT     XMIT_FISRT_8BIT, R7.b1, 1                              \n"
			"XMIT_LAST_8BIT:                                                     \n"
			"    LSR      r24, r24, 8                                            \n"
			"    JAL      r30.w0, PRESACLE_TX_DATA                               \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    JMP      TX_DONE                                                \n"
			"XMIT_FISRT_8BIT:                                                    \n"
			"    AND      r24, r24, 0x00FF                                       \n"
			"    JAL      r30.w0, PRESACLE_TX_DATA                               \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    ADD      R7.b1, R7.b1, 8                                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    MOV      r22, R5.w0                                             \n"
			"    AND      r22, r22, 0xF                                          \n"
			"    QBGE     TX_DONE, r22, 0x8                                      \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"PRE_SCALAR4:                                                        \n"
			"    MOV      r22, R7.b1                                             \n"
			"    QBGT     XMIT_FIRST_4BIT, r22, 1                                \n"
			"XMIT_NXT_4BIT:                                                      \n"
			"    AND      r23, R5.w0, 0xF                                        \n"
			"    SUB      r23, r23, R7.b1                                        \n"
			"    QBLT     MORE_DATA4, r23, 4                                     \n"
			"    LSR      r24, r24, r22                                          \n"
			"    AND      r24, r24, 0xF                                          \n"
			"    JAL      r30.w0, PRESACLE_TX_DATA                               \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    JMP      CHK_TX_DONE                                            \n"
			"MORE_DATA4:                                                         \n"
			"    LSR      r24, r24, r22                                          \n"
			"    AND      r24, r24, 0xF                                          \n"
			"    JAL      r30.w0, PRESACLE_TX_DATA                               \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"CHK_TX_DONE:                                                        \n"
			"    ADD      R7.b1, R7.b1, 4                                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    AND      r23, R5.w0, 0xF                                        \n"
			"    QBGE     TX_DONE, r23, R7.b1                                    \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"XMIT_FIRST_4BIT:                                                    \n"
			"    AND      r24, r24, 0xF                                          \n"
			"    JAL      r30.w0, PRESACLE_TX_DATA                               \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    ADD      R7.b1, R7.b1, 4                                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"PRE_SCALAR6:                                                        \n"
			"    QBGT     XMIT_FIRST_3BIT, R7.b1, 1                              \n"
			"GENERIC_TRANSMIT_BLOCK:                                             \n"
			"    LDI      R13.b3, 0x0                                            \n"
			"    XOR      r21.b1, r21.b1, r21.b1                                 \n"
			"LOAD_BITS_LOOP_FOR6:                                                \n"
			"    AND      r23, R5.w0, 0xF                                        \n"
			"    QBLT     XMIT_NXT_3BIT, r23, R7.b1                              \n"
			"XMIT_MORE_BITS:                                                     \n"
			"    ADD      R7.b0, R7.b0, 1                                        \n"
			"    SBBO     &R7.b0, R8, 12,  1                                     \n"
			"    XOR      R7.b1, R7.b1, R7.b1                                    \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    XOR      R7.w2, R7.w2, R7.w2                                    \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    RSB      r22, R13.b3, 0x10                                      \n"
			"    XOR      r24, r24, r24                                          \n"
			"    NOT      r24, r24                                               \n"
			"    RSB      r21.b1, r22, 16                                        \n"
			"    XOR      r23, r23, r23                                          \n"
			"    AND      r23, r24, 0x1                                          \n"
			"    LSL      r23, r23, r21.b1                                       \n"
			"SET_BIT_BIT:                                                        \n"
			"    OR       r28.w0, r28.w0, r23                                    \n"
			"    LSL      r23, r23, 1                                            \n"
			"    SUB      r22, r22, 1                                            \n"
			"    QBLE     SET_BIT_BIT, r22, 1                                    \n"
			"    LDI      R13.b3, 16                                             \n"
			"    JMP      CHK_MORE_PRESCALAR                                     \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"XMIT_NXT_3BIT:                                                      \n"
			"    QBLT     CHK_MORE_PRESCALAR, R13.b3, 0x10                       \n"
			"BIT_LOAD16:                                                         \n"
			"    LDI      r23, 0x03FF                                            \n"
			"    AND      r22, r23, R4.w2                                        \n"
			"    RSB      r23, R13.b3, 16                                        \n"
			"    SUB      r22, r22, R7.w2                                        \n"
			"    MIN      r22, r22, r23                                          \n"
			"    JAL      r30.w0, READ_TX_DATA                                   \n"
			"    LSR      r24, r24, R7.b1                                        \n"
			"    AND      r23, r24, 0x1                                          \n"
			"    MOV      r25, r22                                               \n"
			"    LSL      r23, r23, R13.b3                                       \n"
			"PRESCALE_NXT_BIT:                                                   \n"
			"    OR       r28.w0, r28.w0, r23                                    \n"
			"    LSL      r23, r23, 1                                            \n"
			"    SUB      r22, r22, 1                                            \n"
			"    QBLE     PRESCALE_NXT_BIT, r22, 1                               \n"
			"    ADD      R13.b3, R13.b3, r25                                    \n"
			"    ADD      R7.w2, R7.w2, r25                                      \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    LDI      r23, 0x03FF                                            \n"
			"    AND      r22, r23, R4.w2                                        \n"
			"    QBGT     CHK_MORE_PRESCALAR, R7.w2, r22                         \n"
			"TX_DONE_CNTR6:                                                      \n"
			"    ADD      R7.b1, R7.b1, 1                                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    XOR      R7.w2, R7.w2, R7.w2                                    \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"CHK_MORE_PRESCALAR:                                                 \n"
			"    QBGT     LOAD_BITS_LOOP_FOR6, R13.b3, 0x10                      \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"XMIT_FIRST_3BIT:                                                    \n"
			"    AND      r24, r24, 0x7                                          \n"
			"    LDI      r23, 12                                                \n"
			"    XOR      r28.w0, r28.w0, r28.w0                                 \n"
			"    XOR      r21.b1, r21.b1, r21.b1                                 \n"
			"    JAL      r30.w0, BYTE_LOOP                                      \n"
			"    LDI      r22, 0x4                                               \n"
			"    XOR      r23, r23, r23                                          \n"
			"    AND      r23, r24, 0x1                                          \n"
			"    LSL      r23, r23, 0xc                                          \n"
			"PRESCALE_LAST_4BIT:                                                 \n"
			"    OR       r28.w0, r28.w0, r23                                    \n"
			"    LSL      r23, r23, 1                                            \n"
			"    SUB      r22, r22, 1                                            \n"
			"    QBLE     PRESCALE_LAST_4BIT, r22, 1                             \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    ADD      R7.b1, R7.b1, 2                                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    ADD      R7.w2, R7.w2, 4                                        \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"PRE_SCALAR12:                                                       \n"
			"    QBGT     XMIT_FIRST_2BIT, R7.b1, 1                              \n"
			"    JMP      GENERIC_TRANSMIT_BLOCK                                 \n"
			"XMIT_FIRST_2BIT:                                                    \n"
			"    AND      r24, r24, 0x3                                          \n"
			"    LDI      r21.b1, 0x0                                            \n"
			"    LDI      r23, 12                                                \n"
			"    XOR      r21.b1, r21.b1, r21.b1                                 \n"
			"    JAL      r30.w0, BYTE_LOOP                                      \n"
			"    XOR      r23, r23, r23                                          \n"
			"    AND      r23, r24, 0x1                                          \n"
			"    LDI      r22, 4                                                 \n"
			"    LSL      r23, r23, 0xC                                          \n"
			"PRESCALE_4BIT:                                                      \n"
			"    OR       r28.w0, r28.w0, r23                                    \n"
			"    LSL      r23, r23, 1                                            \n"
			"    SUB      r22, r22, 1                                            \n"
			"    QBLE     PRESCALE_4BIT, r22, 1                                  \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    ADD      R7.b1, R7.b1, 1                                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    ADD      R7.w2, R7.w2, 4                                        \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"PRE_SCALAR16:                                                       \n"
			"    QBGT     XMIT_FIRST_16, R7.b1, 1                                \n"
			"    JMP      GENERIC_TRANSMIT_BLOCK                                 \n"
			"XMIT_FIRST_16:                                                      \n"
			"    AND      r24, r24, 0x2                                          \n"
			"    LDI      r21.b1, 0x0                                            \n"
			"    LDI      r23, 16                                                \n"
			"    XOR      r28.w0, r28.w0, r28.w0                                 \n"
			"    XOR      r21.b1, r21.b1, r21.b1                                 \n"
			"    JAL      r30.w0, BYTE_LOOP                                      \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    ADD      R7.b1, R7.b1, 1                                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    ADD      R7.w2, R7.w2, 0                                        \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"PRE_SCALAR24:                                                       \n"
			"    QBGT     XMIT_FIRST_24, R7.b1, 1                                \n"
			"    JMP      GENERIC_TRANSMIT_BLOCK                                 \n"
			"XMIT_FIRST_24:                                                      \n"
			"    LDI      r23, 0x03FF                                            \n"
			"    AND      r22, r23, R4.w2                                        \n"
			"    SUB      r22, r22, R7.w2                                        \n"
			"    QBLE     PRESCALE_START_BIT, r22, 16                            \n"
			"PRESCALE_FIRST_DATA_BIT:                                            \n"
			"    XOR      r24, r24, r24                                          \n"
			"    ADD      R7.b1, R7.b1, 1                                        \n"
			"    JAL      r30.w0, READ_TX_DATA                                   \n"
			"    LSR      r24, r24, R7.b1                                        \n"
			"    AND      r23, r24, 0x1                                          \n"
			"    LSL      r23, r23, r22                                          \n"
			"    RSB      r22, r22, 16                                           \n"
			"    MOV      R7.w2, r22                                             \n"
			"PRESCALE_FIRST_DAT_BIT:                                             \n"
			"    OR       r28.w0, r28.w0, r23                                    \n"
			"    LSL      r23, r23, 1                                            \n"
			"    SUB      r22, r22, 1                                            \n"
			"    QBLE     PRESCALE_FIRST_DAT_BIT, r22, 1                         \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"PRESCALE_START_BIT:                                                 \n"
			"    LDI      r22, 0x10                                              \n"
			"    LDI      r23, 0x10                                              \n"
			"    XOR      r21.b1, r21.b1, r21.b1                                 \n"
			"    JAL      r30.w0, BITS_LOOP                                      \n"
			"    JAL      r30.w0, TRANSMIT_PRESCALED_DATA                        \n"
			"    ADD      R7.w2, R7.w2, 16                                       \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"LOAD_TX_COMMON_INFO:                                                \n"
			"    QBEQ     LOAD_TX_FORMAT_ADDRESS_DONE, R3.b1, 0x1                \n"
			"    JAL      r30.w0, LOAD_TX_FORMAT_ADDRESS                         \n"
			"LOAD_TX_FORMAT_ADDRESS_DONE:                                        \n"
			"    JMP      LOCATE_SR_XBUF_SRCTL                                   \n"
			"LOCATE_SR_XBUF_SRCTL_DONE:                                          \n"
			"    JMP      CHK_TX_DATA_FORMAT                                     \n"
			"CHK_TX_DATA_FORMAT_DONE:                                            \n"
			"    JMP      ENABLE_TX_SERIALIZER                                   \n"
			"LOCATE_SR_XBUF_SRCTL:                                               \n"
			"    AND      r22, R4.b1, 0x0F                                       \n"
			"    LSL      r22, r22, 2                                            \n"
			"    MOV      r24, R13.w0                                            \n"
			"    LDI      r25, 0x20                                              \n"
			"    LDI      R11.w0, (0x01D00180) & 0xFFFF                          \n"
			"    LDI      R11.w2, (0x01D00180) >> 16                             \n"
			"    ADD      R11, R11, r22                                          \n"
			"    ADD      r23, r25, 0                                            \n"
			"    SBBO     &R11, r24, r23,  4                                     \n"
			"    LDI      R12.w0, (0x01D00200) & 0xFFFF                          \n"
			"    LDI      R12.w2, (0x01D00200) >> 16                             \n"
			"    ADD      R12, R12, r22                                          \n"
			"    ADD      r23, r25, 4                                            \n"
			"    SBBO     &R12, r24, r23,  4                                     \n"
			"    MOV      R13.b2, R5.b1                                         \n"
			"    ADD      r23, r25, 10                                           \n"
			"    SBBO     &R13.b2, r24, r23,  1                                  \n"
			"    ADD      r23, r25, 8                                            \n"
			"    SBBO     &R13.w0, r24, r23,  2                                  \n"
			"    LDI      R13.b3, 0x00                                           \n"
			"    ADD      r23, r25, 11                                           \n"
			"    SBBO     &R13.b3, r24, r23,  1                                  \n"
			"    JMP      LOCATE_SR_XBUF_SRCTL_DONE                              \n"
			"CHK_TX_DATA_FORMAT:                                                 \n"
			"    QBEQ     CHK_TX_DATA_FORMAT_BITS, R7.w2, 0                      \n"
			"    JMP      CHK_TX_DATA_FORMAT_DONE                                \n"
			"CHK_TX_DATA_FORMAT_BITS:                                            \n"
			"    QBEQ     CHK_TX_DATA_FORMAT_BYTE, R7.b1, 0                      \n"
			"    JMP      CHK_TX_DATA_FORMAT_DONE                                \n"
			"CHK_TX_DATA_FORMAT_BYTE:                                            \n"
			"    QBEQ     TX_DATA_FORMAT, R7.b0, 0                               \n"
			"    JMP      CHK_TX_DATA_FORMAT_DONE                                \n"
			"TX_DATA_FORMAT:                                                     \n"
			"    XOR      r22, r22, r22                                          \n"
			"    NOT      r22, r22                                               \n"
			"    SUB      r23, R5.b0, 1                                          \n"
			"    LSL      r22, r22, r23                                          \n"
			"    XOR      r23, r23, r23                                          \n"
			"    MOV      r24, R13.w0                                            \n"
			"    AND      r21.b0, R5.b0, 0xF                                     \n"
			"    SUB      r21.b0, r21.b0, 2                                      \n"
			"TX_DATA_FORMAT_LOOP:                                                \n"
			"    LBBO     &r28, R6, 0x00, 2                                      \n"
			"    LSL      r28, r28, 1                                            \n"
			"    OR       r28, r28, r22                                          \n"
			"    SBBO     &r28.w0, r24, r23, 2                                   \n"
			"    ADD      r23, r23, 2                                            \n"
			"    QBGE     INC_ADDR_BY_ONE, r21.b0, 0x8                           \n"
			"    ADD      R6, R6, 1                                              \n"
			"INC_ADDR_BY_ONE:                                                    \n"
			"    ADD      R6, R6, 1                                              \n"
			"    QBEQ     CHK_TX_DATA_FORMAT_DONE, R13.b2, 0                     \n"
			"    SUB      R13.b2, R13.b2, 1                                      \n"
			"    JMP      TX_DATA_FORMAT_LOOP                                    \n"
			"READ_TX_DATA:                                                       \n"
			"    MOV      r24, R13.w0                                            \n"
			"    LSL      r25, R7.b0, 1                                          \n"
			"    LBBO     &r24, r24, r25, 2                                      \n"
			"    jmp      r30.w0                                                 \n"
			"LOAD_TX_FORMAT_ADDRESS:                                             \n"
			"    QBEQ     TX_CH0_FMT_ADDR, R10.b2, 0                             \n"
			"    QBEQ     TX_CH2_FMT_ADDR, R10.b2, 2                             \n"
			"    QBEQ     TX_CH4_FMT_ADDR, R10.b2, 4                             \n"
			"    QBEQ     TX_CH6_FMT_ADDR, R10.b2, 6                             \n"
			"    jmp      r30.w0                                                 \n"
			"TX_CH0_FMT_ADDR:                                                    \n"
			"    LDI      R13.w0, 0x090                                          \n"
			"    jmp      r30.w0                                                 \n"
			"TX_CH2_FMT_ADDR:                                                    \n"
			"    LDI      R13.w0, 0x0E0                                          \n"
			"    jmp      r30.w0                                                 \n"
			"TX_CH4_FMT_ADDR:                                                    \n"
			"    LDI      R13.w0, 0x130                                          \n"
			"    jmp      r30.w0                                                 \n"
			"TX_CH6_FMT_ADDR:                                                    \n"
			"    LDI      R13.w0, 0x180                                          \n"
			"    jmp      r30.w0                                                 \n"
			"PRESACLE_TX_DATA:                                                   \n"
			"    XOR      r21.b1, r21.b1, r21.b1                                 \n"
			"    LDI      r23, 16                                                \n"
			"    XOR      r28.w0, r28.w0, r28.w0                                 \n"
			"BYTE_LOOP:                                                          \n"
			"    LDI      r25, 0x03FF                                            \n"
			"    AND      r22, r25, R4.w2                                        \n"
			"BITS_LOOP:                                                          \n"
			"    XOR      r25, r25, r25                                          \n"
			"    AND      r25, r24, 0x1                                          \n"
			"    LSL      r25, r25, r21.b1                                       \n"
			"    OR       r28.w0, r28.w0, r25                                    \n"
			"    ADD      r21.b1, r21.b1, 1                                      \n"
			"    SUB      r23, r23, 1                                            \n"
			"    SUB      r22, r22, 1                                            \n"
			"    QBLE     BITS_LOOP, r22, 1                                      \n"
			"    LSR      r24, r24, 1                                            \n"
			"    QBLE     BYTE_LOOP, r23, 1                                      \n"
			"    jmp      r30.w0                                                 \n"
			"TRANSMIT_PRESCALED_DATA:                                            \n"
			"    LBCO     &r22, C25, 0xc0, 4                                     \n"
			"    QBBC     WRITE_TO_XBUF, r22, 0x8                                \n"
			"    LDI      r22, 0xFFFF                                            \n"
			"    SBCO     &r22, C25, 0xc0, 4                                     \n"
			"WRITE_TO_XBUF:                                                      \n"
			"    SBBO     &r28.w0, R12, 00, 4                                    \n"
			"    jmp      r30.w0                                                 \n"
			"TX_DONE:                                                            \n"
			"    XOR      R7.b1, R7.b1, R7.b1                                    \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    ADD      R7.b0, R7.b0, 1                                        \n"
			"    SBBO     &R7.b0, R8, 12,  1                                     \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"TxInterruptServiceRequestHndlr:                                     \n"
			"    LDI      R8, 0x0000                                             \n"
			"    LDI      R10.w0, 0x0000                                         \n"
			"    LDI      R10.b2, 0x00                                           \n"
			"    LDI      R13.w0, 0x90                                           \n"
			"SERCH_MAPPED_TX_CHN:                                                \n"
			"    ADD      r22, R10.w0, 7                                         \n"
			"    LBBO     &R5.b3, R8, r22,  1                                    \n"
			"    QBBC     NEXT_TX_CHN, R5.b3, 7                                  \n"
			"    ADD      r22, R13.w0, 0x20                                      \n"
			"    LBBO     &r23, r22, 0, 4                                        \n"
			"    LBBO     &r22, r23, 0, 4                                        \n"
			"    QBBS     MAPPED_TX_CHN_FOUND, r22, 4                            \n"
			"NEXT_TX_CHN:                                                        \n"
			"    QBEQ     PRU_TX_ONLY_MODE, R3.b1, 0x1                           \n"
			"    ADD      R10.w0, R10.w0, 0x20                                   \n"
			"    ADD      R10.b2, R10.b2, 0x02                                   \n"
			"    ADD      R13.w0, R13.w0, 0x50                                   \n"
			"    QBGE     SERCH_MAPPED_TX_CHN, R10.b2, (8 - 1)                   \n"
			"    JMP      CORE_LOOP                                              \n"
			"PRU_TX_ONLY_MODE:                                                   \n"
			"    ADD      R10.w0, R10.w0, 0x10                                   \n"
			"    ADD      R10.b2, R10.b2, 0x01                                   \n"
			"    ADD      R13.w0, R13.w0, 0x2C                                   \n"
			"    QBGE     SERCH_MAPPED_TX_CHN, R10.b2, (8 - 1)                   \n"
			"    JMP      CORE_LOOP                                              \n"
			"MAPPED_TX_CHN_FOUND:                                                \n"
			"    LBBO     &R4.w0, R8, R10.w0,  16                                \n"
			"    ADD      R8, R8, R10.w0                                         \n"
			"    QBEQ     PRUx_MODE_TX_ONLY, R3.b1, 0x1                          \n"
			"    QBEQ     CORE_LOOP, R3.b1, 0x00                                 \n"
			"PRUx_MODE_TX_ONLY:                                                  \n"
			"    ADD      r22, R13.w0, 0x20                                      \n"
			"    LBBO     &R11, r22, 0, 12                                       \n"
			"    LSR      r22, R5.w0, 0x8                                        \n"
			"    AND      r22, r22, 0x0F                                         \n"
			"    ADD      r22, r22, 0x01                                         \n"
			"    QBLT     TxServiceReqHndlLoop, r22, R7.b0                       \n"
			"    QBBS     DECLARE_COMPLETE, R5.b2, 0                             \n"
			"    NOT      r22, r20                                               \n"
			"    SBBO     &r22, R12, 00, 4                                       \n"
			"    JMP      CORE_LOOP                                              \n"
			"DECLARE_COMPLETE:                                                   \n"
			"    SET      R5.b2, R5.b2, 1                                        \n"
			"    CLR      R5.b2, R5.b2, 0                                        \n"
			"    SBBO     &R5.b2, R8, 6,  1                                      \n"
			"    LBBO     &R2.w0, r20, 0x080, 2                                  \n"
			"    QBBC     CORE_LOOP, R2.w0, R10.b2                               \n"
			"    LBBO     &R2.w2, r20, 0x082, 2                                  \n"
			"    SET      R2.w2, R2.w2, R10.b2                                   \n"
			"    SBBO     &R2.w2, r20, 0x082, 2                                  \n"
			"    JMP      PRU_TO_HOST_INTERRUPT                                  \n"
			"CORE_LOOP:                                                          \n"
			"    QBEQ     CORE_LOOP, R3.b1, 0x00                                 \n"
			"ARM_DSP_EVENT:                                                      \n"
			"    QBEQ     CORE_LOOP_PRU1, R3.b0, 1                               \n"
			"CORE_LOOP_PRU0:                                                     \n"
			"    WBS      r31, 30                                                \n"
			"    LDI      r23.w0, 0x204 & 0xFFFF                                 \n"
			"    LDI      r23.w2, 0x204 >> 16                                    \n"
			"    LBCO     &r22, C0, r23, 4                                       \n"
			"    QBBS     CHN_SEARCH, r22, 0                                     \n"
			"    LDI      r22.w0, 31 & 0xFFFF                                    \n"
			"    LDI      r22.w2, 31 >> 16                                       \n"
			"    SBCO     &r22, C0, 0x24, 4                                      \n"
			"    JMP      MCASP_EVENT                                            \n"
			"CORE_LOOP_PRU1:                                                     \n"
			"    WBS      r31, 31                                                \n"
			"    LBCO     &r22, C25, 0xc0, 4                                     \n"
			"    QBBC     CHN_SEARCH, r22, 5                                     \n"
			"    LDI      r22.w0, 50 & 0xFFFF                                    \n"
			"    LDI      r22.w2, 50 >> 16                                       \n"
			"    SBCO     &r22, C0, 0x24, 4                                      \n"
			"    JMP      TxInterruptServiceRequestHndlr                         \n"
			"MCASP_EVENT:                                                        \n"
			"    QBEQ     MCASP_TX_EVNT, R3.b1, 0x1                              \n"
			"    QBNE     RX_TX_PROCESS, R3.b1, 0x2                              \n"
			"    LBCO     &r22, C25, 0xc0, 4                                     \n"
			"    QBBC     RX_TX_PROCESS, r22, 5                                  \n"
			"    LDI      r22.w0, 50 & 0xFFFF                                    \n"
			"    LDI      r22.w2, 50 >> 16                                       \n"
			"    SBCO     &r22, C0, 0x20, 4                                      \n"
			"RX_TX_PROCESS:                                                      \n"
			"    LBCO     &r22, C25, 0x80, 4                                     \n"
			"    QBBS     RxInterruptServiceRequestHndlr, r22, 5                 \n"
			"    QBNE     CORE_LOOP, R3.b1, 0x3                                  \n"
			"MCASP_TX_EVNT:                                                      \n"
			"    LBCO     &r22, C25, 0xc0, 4                                     \n"
			"    QBBS     TxInterruptServiceRequestHndlr, r22, 5                 \n"
			"    QBEQ     CORE_LOOP, R3.b1, 0x3                                  \n"
			"CHN_SEARCH:                                                         \n"
			"    LDI      r24.w0, 0x00000001 & 0xFFFF                            \n"
			"    LDI      r24.w2, 0x00000001 >> 16                               \n"
			"    LSL      r24, r24, R3.b0                                        \n"
			"    LDI      r22.w0, 0x284 & 0xFFFF                                 \n"
			"    LDI      r22.w2, 0x284 >> 16                                    \n"
			"    SBCO     &r24, C0, r22, 4                                       \n"
			"    LBBO     &R2.w0, r20, 0x080,  8                                 \n"
			"    LDI      R8, 0x0000                                             \n"
			"    LDI      R10.w0, 0x0000                                         \n"
			"    LDI      R10.b2, 0x00                                           \n"
			"    XOR      R13.w0, R13.w0, R13.w0                                 \n"
			"    XOR      R9, R9, R9                                             \n"
			"    LDI      R13.w0, 0x90                                           \n"
			"    LDI      R9, 0x90                                               \n"
			"CHN_ACTIVE:                                                         \n"
			"    LBBO     &R4.w0, R8, R10.w0,  2                                 \n"
			"    QBBS     CHN_SERACH_RTN, R4.w0, 0x2                             \n"
			"    ADD      R10.w0, R10.w0, 0x10                                   \n"
			"    ADD      R10.b2, R10.b2, 0x01                                   \n"
			"    ADD      R13.w0, R13.w0, 0x2C                                   \n"
			"    ADD      R9, R9, 0x20                                           \n"
			"    QBLT     MCASP_EVENT, R10.b2, (8 - 1)                           \n"
			"    JMP      CHN_ACTIVE                                             \n"
			"CHN_SERACH_RTN:                                                     \n"
			"    LBBO     &R4.w0, R8, R10.w0,  16                                \n"
			"    ADD      R8, R8, R10.w0                                         \n"
			"    AND      r22.w0, R4.w0, 0x3                                     \n"
			"    QBEQ     TxServiceRequestHndlr, r22.w0, 0x1                     \n"
			"    QBEQ     RxServiceRequestHndlr, r22.w0, 0x2                     \n"
			"    JMP      CORE_LOOP                                              \n"
			"PRU_TO_HOST_INTERRUPT:                                              \n"
			"    LDI      r22, 0                                                 \n"
			"    QBEQ     EVTOUT_PRU0_EVENTS, R3.b0, 0                           \n"
			"    QBEQ     EVTOUT_PRU1_EVENTS, R3.b0, 1                           \n"
			"EVTOUT_PRU0_EVENTS:                                                 \n"
			"    ADD      r22, r22, 34                                           \n"
			"    JMP      EVTOUT_SYSEVT_INIT                                     \n"
			"EVTOUT_PRU1_EVENTS:                                                 \n"
			"    ADD      r22, r22, 42                                           \n"
			"EVTOUT_SYSEVT_INIT:                                                 \n"
			"    ADD      r22, r22, R10.b2                                       \n"
			"EVTOUT_GEN:                                                         \n"
			"    SBCO     &r22, C0, 0x24, 4                                      \n"
			"    SBCO     &r22, C0, 0x28, 4                                      \n"
			"    MOV      r31.w0, r22.w0                                         \n"
			"    JMP      MCASP_EVENT                                            \n"
			"RxServiceRequestHndlr:                                              \n"
			"    LBBO     &r1.w0, r20, 0x088, 2                                  \n"
			"    LBBO     &R2.w2, r20, 0x082, 2                                  \n"
			"    CLR      R2.w2, R2.w2, R10.b2                                   \n"
			"    SBBO     &R2.w2, r20, 0x082, 2                                  \n"
			"    CLR      R4.w0, R4.w0, 0x2                                      \n"
			"    SBBO     &R4.w0, R8, 0,  2                                      \n"
			"    CLR      R5.b2, R5.b2, 6                                        \n"
			"    SET      R5.b2, R5.b2, 0                                        \n"
			"    SBBO     &R5.b2, R8, 6,  1                                      \n"
			"    SET      R5.b3, R5.b3, 7                                        \n"
			"    SBBO     &R5.b3, R8, 7,  1                                      \n"
			"RX_CONTEXT_INIT:                                                    \n"
			"    QBEQ     PRUxxx_MODE_RX_ONLY, R3.b1, 0x2                        \n"
			"    JAL      r30.w0, LOAD_RX_CONTEXT_ADDRESS                        \n"
			"PRUxxx_MODE_RX_ONLY:                                                \n"
			"    AND      r22, R4.b1, 0x0F                                       \n"
			"    LSL      r22, r22, 2                                            \n"
			"    LDI      R12.w0, (0x01D00180) & 0xFFFF                          \n"
			"    LDI      R12.w2, (0x01D00180) >> 16                             \n"
			"    ADD      R12, R12, r22                                          \n"
			"    SBBO     &R12, R9, 4,  4                                        \n"
			"    LDI      R11.w0, (0x01D00280) & 0xFFFF                          \n"
			"    LDI      R11.w2, (0x01D00280) >> 16                             \n"
			"    ADD      R11, R11, r22                                          \n"
			"    SBBO     &R11, R9, 0,  4                                        \n"
			"    XOR      R16.w0, R16.w0, R16.w0                                 \n"
			"    SBBO     &R16.w0, R9, 20,  2                                    \n"
			"    LBBO     &r23, R12, 0, 4                                        \n"
			"    AND      r23, r23, 0x3                                          \n"
			"    QBEQ     CLR_RSTAT, r23, 0x2                                    \n"
			"    LDI      r23.w0, 0x000E & 0xFFFF                                \n"
			"    LDI      r23.w2, 0x000E >> 16                                   \n"
			"    SBBO     &r23, R12, 0, 4                                        \n"
			"CLR_RSTAT:                                                          \n"
			"    LDI      r22.w0, 0xFFFF & 0xFFFF                                \n"
			"    LDI      r22.w2, 0xFFFF >> 16                                   \n"
			"    SBCO     &r22, C25, 0x80, 4                                     \n"
			"    JMP      MCASP_EVENT                                            \n"
			"RxInterruptServiceRequestHndlr:                                     \n"
			"    LDI      R8, 0x0000                                             \n"
			"    QBEQ     PRUx_MODE_RX_ONLY, R3.b1, 0x2                          \n"
			"    ADD      R10.w0, r20.w0, 0x10                                   \n"
			"    LDI      R10.b2, 0x01                                           \n"
			"    LDI      R9, 0x0C0                                              \n"
			"    JMP      SERCH_ACTIVE_RX_CHN_RX                                 \n"
			"PRUx_MODE_RX_ONLY:                                                  \n"
			"    LDI      R10.w0, 0x00                                           \n"
			"    LDI      R10.b2, 0x00                                           \n"
			"    LDI      R9, 0x90                                               \n"
			"SERCH_ACTIVE_RX_CHN_RX:                                             \n"
			"    ADD      r22, R10.w0, 7                                         \n"
			"    LBBO     &R5.b3, R8, r22,  1                                    \n"
			"    QBBC     NEXT_RX_CHN, R5.b3, 7                                  \n"
			"    LBBO     &r22, R9, 4, 4                                         \n"
			"    LBBO     &r23, r22, 0, 4                                        \n"
			"    QBBS     ACTIVE_RX_CHN_FOUND, r23, 5                            \n"
			"NEXT_RX_CHN:                                                        \n"
			"    QBEQ     PRUxx_MODE_RX_ONLY, R3.b1, 0x2                         \n"
			"    ADD      R10.w0, R10.w0, 0x20                                   \n"
			"    ADD      R10.b2, R10.b2, 0x2                                    \n"
			"    ADD      R9, R9, 0x50                                           \n"
			"    QBGE     SERCH_ACTIVE_RX_CHN_RX, R10.b2, (8 - 1)                \n"
			"    JMP      CORE_LOOP                                              \n"
			"PRUxx_MODE_RX_ONLY:                                                 \n"
			"    ADD      R10.w0, R10.w0, 0x10                                   \n"
			"    ADD      R10.b2, R10.b2, 0x1                                    \n"
			"    ADD      R9, R9, 0x20                                           \n"
			"    QBGE     SERCH_ACTIVE_RX_CHN_RX, R10.b2, (8 - 1)                \n"
			"    JMP      CORE_LOOP                                              \n"
			"ACTIVE_RX_CHN_FOUND:                                                \n"
			"    LBBO     &R4.w0, R8, R10.w0,  16                                \n"
			"    LBBO     &R11, R9, 0, 24                                        \n"
			"    ADD      R8, R8, R10.w0                                         \n"
			"    LBCO     &r22, C25, 0x80, 4                                     \n"
			"    QBBC     RX_PROCESSING_INIT, r22, 8                             \n"
			"    LDI      r22.w0, 0xFFFF & 0xFFFF                                \n"
			"    LDI      r22.w2, 0xFFFF >> 16                                   \n"
			"    SBCO     &r22, C25, 0x80, 4                                     \n"
			"RX_PROCESSING_INIT:                                                 \n"
			"    XOR      r19, r19, r19                                          \n"
			"    LBBO     &r22, R11, 0, 4                                        \n"
			"    OR       r19, r19, r22                                          \n"
			"    QBLT     READ_CURRENT, R7.b1, 0                                 \n"
			"    QBLT     READ_CURRENT, R7.w2, 0                                 \n"
			"    QBGE     READ_CURRENT, R16.b2, 16                               \n"
			"    LMBD     r25, r22, 0                                            \n"
			"    QBGT     START_BIT_TRANSITION, r25, 32                          \n"
			"    LDI      R16.b2, 0xff                                           \n"
			"    SBBO     &R16.b2, R9, 22,  1                                    \n"
			"    QBBC     RxInterruptServiceRequestHndlr, R4.w2, 14              \n"
			"    QBBC     RxInterruptServiceRequestHndlr, R5.b2, 0               \n"
			"    QBEQ     RxInterruptServiceRequestHndlr, R7.b0, 0               \n"
			"    LSR      r22, R5.w0, 0x8                                        \n"
			"    AND      r22, r22, 0x0F                                         \n"
			"    ADD      r22, r22, 0x01                                         \n"
			"    QBEQ     RxInterruptServiceRequestHndlr, R7.b0, r22             \n"
			"    ADD      R16.w0, R16.w0, 1                                      \n"
			"    SBBO     &R16.w0, R9, 20,  2                                    \n"
			"    QBGE     RxInterruptServiceRequestHndlr, R16.w0, r1.w0          \n"
			"    SET      R5.b2, R5.b2, 6                                        \n"
			"    CLR      R4.w2, R4.w2, 14                                       \n"
			"    SBBO     &R4.w2, R8, 2,  2                                      \n"
			"    XOR      R16.w0, R16.w0, R16.w0                                 \n"
			"    SBBO     &R16.w0, R9, 20,  2                                    \n"
			"    JMP      RX_CHN_INTR                                            \n"
			"START_BIT_TRANSITION:                                               \n"
			"    XOR      R16.w0, R16.w0, R16.w0                                 \n"
			"    SBBO     &R16.w0, R9, 20,  2                                    \n"
			"    LSR      r23, R4.w2, 0xA                                        \n"
			"    AND      r23, r23, 0x3                                          \n"
			"    QBEQ     OVER_SAMPLE_SIZE8BIT, r23, 0x0                         \n"
			"    QBEQ     OVER_SAMPLE_SIZE8BIT, r23, 0x1                         \n"
			"    QBEQ     OVER_SAMPLE_SIZE16BIT, r23, 0x2                        \n"
			"OVER_SAMPLE_SIZE8BIT:                                               \n"
			"    SUB      R16.b2, r25, 0x4                                       \n"
			"    AND      R16.b2, R16.b2, 7                                      \n"
			"    SBBO     &R16.b2, R9, 22,  1                                    \n"
			"    QBLE     READ_CURRENT, r25, 0x4                                 \n"
			"    JMP      RxInterruptServiceRequestHndlr                         \n"
			"OVER_SAMPLE_SIZE16BIT:                                              \n"
			"    SUB      R16.b2, r25, 0x8                                       \n"
			"    AND      R16.b2, R16.b2, 15                                     \n"
			"    SBBO     &R16.b2, R9, 22,  1                                    \n"
			"    QBLE     READ_CURRENT, r25, 0x8                                 \n"
			"    JMP      RxInterruptServiceRequestHndlr                         \n"
			"READ_CURRENT:                                                       \n"
			"    XOR      r21.b1, r21.b1, r21.b1                                 \n"
			"    QBBC     READ_ZERO, r22, R16.b2                                 \n"
			"    ADD      r21.b1, r21.b1, 1                                      \n"
			"READ_ZERO:                                                          \n"
			"    QBLT     RX_BIT_RECVD, R7.b1, 0                                 \n"
			"    QBEQ     START_CONDITION, r21.b1, 0                             \n"
			"    QBEQ     START_CONDITION, R7.w2, 0                              \n"
			"    XOR      R7.w2, R7.w2, R7.w2                                    \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    JMP      RxInterruptServiceRequestHndlr                         \n"
			"START_CONDITION:                                                    \n"
			"    ADD      R7.w2, R7.w2, 1                                        \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    LDI      r23, 0x03FF                                            \n"
			"    AND      r23, r23, R4.w2                                        \n"
			"    QBGE     START_BIT_RECIVED, r23, R7.w2                          \n"
			"    JMP      RxInterruptServiceRequestHndlr                         \n"
			"START_BIT_RECIVED:                                                  \n"
			"    ADD      R7.b1, R7.b1, 1                                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    XOR      R7.w2, R7.w2, R7.w2                                    \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    JMP      RxInterruptServiceRequestHndlr                         \n"
			"RX_BIT_RECVD:                                                       \n"
			"    XOR      r22, r22, r22                                          \n"
			"    QBEQ     RX_DATA_BIT_ZERO, r21.b1, 0                            \n"
			"    OR       r22, r22, 0x1                                          \n"
			"RX_DATA_BIT_ZERO:                                                   \n"
			"    QBGE     RX_REPEAT_DONE_CNTR_LT_32, R7.w2, 0x20                 \n"
			"RX_REPEAT_DONE_CNTR_GT_32:                                          \n"
			"    RSB      r23, R7.w2, 0x20                                       \n"
			"    LSL      r22, r22, r23                                          \n"
			"    LBBO     &R15, R9, 16,  4                                       \n"
			"    OR       R15, r22, R15                                          \n"
			"    SBBO     &R15, R9, 16,  4                                       \n"
			"    JMP      RX_REPEAT_COUNT_LESS_THAN_PRESCALR                     \n"
			"RX_REPEAT_DONE_CNTR_LT_32:                                          \n"
			"    LSL      r22, r22, R7.w2                                        \n"
			"    LBBO     &R14, R9, 12,  4                                       \n"
			"    OR       R14, r22, R14                                          \n"
			"    SBBO     &R14, R9, 12,  4                                       \n"
			"RX_REPEAT_COUNT_LESS_THAN_PRESCALR:                                 \n"
			"    ADD      R7.w2, R7.w2, 1                                        \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    LDI      r23, 0x03FF                                            \n"
			"    AND      r23, r23, R4.w2                                        \n"
			"    QBGE     PROCESS_RX_DATA_BIT, r23, R7.w2                        \n"
			"    JMP      RxInterruptServiceRequestHndlr                         \n"
			"PROCESS_RX_DATA_BIT:                                                \n"
			"    LDI      r24, 0x03FF                                            \n"
			"    AND      r24, r24, R4.w2                                        \n"
			"    XOR      r21.b0, r21.b0, r21.b0                                 \n"
			"    XOR      r21.b1, r21.b1, r21.b1                                 \n"
			"    XOR      r23, r23, r23                                          \n"
			"    XOR      r22, r22, r22                                          \n"
			"    LBBO     &r25, R9, 12,  4                                       \n"
			"    QBGE     BIT_CHK_LOOP, r24, 0x20                                \n"
			"PRE_SCALR_GT_32:                                                    \n"
			"    OR       r22, r22, 0x10                                         \n"
			"    QBGT     BIT_CHK_LOOP, r24, 0x30                                \n"
			"PRE_SCALR_GT_48:                                                    \n"
			"    LDI      r24, 0x30                                              \n"
			"BIT_CHK_LOOP:                                                       \n"
			"    QBBC     BIT_RECVD_ZERO, r25, r22                               \n"
			"    ADD      r21.b0, r21.b0, 1                                      \n"
			"    ADD      r22, r22, 1                                            \n"
			"    ADD      r23, r23, 1                                            \n"
			"    QBLT     LOAD_RXDATABITS_HOLDREGHIGH, r23, 0x20                 \n"
			"    QBGT     BIT_CHK_LOOP, r23, r24                                 \n"
			"    JMP      COPY_BIT_RECVD                                         \n"
			"LOAD_RXDATABITS_HOLDREGHIGH:                                        \n"
			"    LBBO     &r25, R9, 16,  4                                       \n"
			"    XOR      r22, r22, r22                                          \n"
			"    XOR      r23, r23, r23                                          \n"
			"    SUB      r24, r24, 0x20                                         \n"
			"    JMP      BIT_CHK_LOOP                                           \n"
			"BIT_RECVD_ZERO:                                                     \n"
			"    ADD      r21.b1, r21.b1, 1                                      \n"
			"    ADD      r22, r22, 1                                            \n"
			"    ADD      r23, r23, 1                                            \n"
			"    QBGT     BIT_CHK_LOOP, r23, r24                                 \n"
			"COPY_BIT_RECVD:                                                     \n"
			"    XOR      r22, r22, r22                                          \n"
			"    QBGE     WRITE_RCVD_BIT_TO_RX_DATAHOLDREG, r21.b0, r21.b1       \n"
			"    OR       r22, r22, 0x1                                          \n"
			"WRITE_RCVD_BIT_TO_RX_DATAHOLDREG:                                   \n"
			"    LSL      r22, r22, R7.b1                                        \n"
			"    LBBO     &R13.w2, R9, 10,  2                                    \n"
			"    OR       R13.w2, R13.w2, r22                                    \n"
			"    SBBO     &R13.w2, R9, 10,  2                                    \n"
			"    ADD      R7.b1, R7.b1, 1                                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    XOR      R7.w2, R7.w2, R7.w2                                    \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    XOR      R14, R14, R14                                          \n"
			"    SBBO     &R14, R9, 12,  4                                       \n"
			"    XOR      R15, R15, R15                                          \n"
			"    SBBO     &R15, R9, 16,  4                                       \n"
			"    AND      r23, R5.w0, 0xF                                        \n"
			"    QBGE     RESET_BITS_CNTR, r23, R7.b1                            \n"
			"    SUB      r23, r23, 1                                            \n"
			"    QBEQ     CHK_RECVD_DATA_FRAME, r23, R7.b1                       \n"
			"    JMP      RxInterruptServiceRequestHndlr                         \n"
			"CHK_RECVD_DATA_FRAME:                                               \n"
			"    RSB      r23, r23, 16                                           \n"
			"    ADD      r23, r23, 0x10                                         \n"
			"    NOT      r22, r20                                               \n"
			"REGHOLD_MSB_ZERO:                                                   \n"
			"    LSR      r22, r22, r23                                          \n"
			"    LBBO     &R13.w2, R9, 10,  2                                    \n"
			"    AND      R13.w2, R13.w2, r22                                    \n"
			"    SBBO     &R13.w2, R9, 10,  2                                    \n"
			"    LSR      R13.w2, R13.w2, 1                                      \n"
			"    LBBO     &R6, R8, 8,  4                                         \n"
			"    AND      r25, R5.w0, 0xF                                        \n"
			"    SUB      r25, r25, 2                                            \n"
			"    MOV      r22, R7.b0                                             \n"
			"    QBGE     WRITE_RX_CHAR_TO_MEM, r25, 0x8                         \n"
			"    LSL      r22, r22, 1                                            \n"
			"WRITE_RX_CHAR_TO_MEM:                                               \n"
			"    SBBO     &R13.w2, R6, r22,  2                                   \n"
			"    JMP      RxInterruptServiceRequestHndlr                         \n"
			"RESET_BITS_CNTR:                                                    \n"
			"    SUB      r24, R7.b1, 1                                          \n"
			"    XOR      R7.b1, R7.b1, R7.b1                                    \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    LDI      r23, 0x03FF                                            \n"
			"    AND      r23, r23, R4.w2                                        \n"
			"    LMBD     r25, r19, 0                                            \n"
			"    QBEQ     INVALID_SAMPLING_PNT, r25, 32                          \n"
			"    LSR      r22, R4.w2, 0xA                                        \n"
			"    AND      r22, r22, 0x3                                          \n"
			"    QBEQ     NXT_FRAME_SAMPLING_16BIT_OVS, r22, 0x2                 \n"
			"NXT_FRAME_SAMPLING_8BIT_OVS:                                        \n"
			"    QBLT     INVALID_SAMPLING_PNT, r25, 4                           \n"
			"CAL_SAMPL_PNT8:                                                     \n"
			"    SUB      R16.b2, r25, 0x4                                       \n"
			"    AND      R16.b2, R16.b2, 7                                      \n"
			"    QBGT     UPDATE_SAMPLING_PNT, r25, 4                            \n"
			"    JMP      NXT_FRAME_SAMPLING_PNT                                 \n"
			"NXT_FRAME_SAMPLING_16BIT_OVS:                                       \n"
			"    QBLT     INVALID_SAMPLING_PNT, r25, 8                           \n"
			"CAL_SAMPL_PNT16:                                                    \n"
			"    SUB      R16.b2, r25, 0x8                                       \n"
			"    AND      R16.b2, R16.b2, 15                                     \n"
			"    QBGT     UPDATE_SAMPLING_PNT, r25, 8                            \n"
			"NXT_FRAME_SAMPLING_PNT:                                             \n"
			"    ADD      R7.w2, R7.w2, 1                                        \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    LDI      r23, 0x03FF                                            \n"
			"    AND      r23, r23, R4.w2                                        \n"
			"    QBLT     UPDATE_SAMPLING_PNT, r23, R7.w2                        \n"
			"START_BIT:                                                          \n"
			"    ADD      R7.b1, R7.b1, 1                                        \n"
			"    SBBO     &R7.b1, R8, 13,  1                                     \n"
			"    XOR      R7.w2, R7.w2, R7.w2                                    \n"
			"    SBBO     &R7.w2, R8, 14,  2                                     \n"
			"    JMP      UPDATE_SAMPLING_PNT                                    \n"
			"INVALID_SAMPLING_PNT:                                               \n"
			"    LDI      R16.b2, 0xff                                           \n"
			"UPDATE_SAMPLING_PNT:                                                \n"
			"    SBBO     &R16.b2, R9, 22,  1                                    \n"
			"    LBBO     &R2.w0, r20, 0x080, 2                                  \n"
			"    LBBO     &R2.w2, r20, 0x082, 2                                  \n"
			"    QBGE     RX_DATA_ZERO, R13.w2, 0                                \n"
			"    QBBC     BIT_CLEARD, R13.w2, r24                                \n"
			"    ADD      R7.b0, R7.b0, 1                                        \n"
			"    SBBO     &R7.b0, R8, 12,  1                                     \n"
			"    XOR      R13.w2, R13.w2, R13.w2                                 \n"
			"    SBBO     &R13.w2, R9, 10,  2                                    \n"
			"    LSR      r22, R5.w0, 0x8                                        \n"
			"    AND      r22, r22, 0x0F                                         \n"
			"    ADD      r22, r22, 0x01                                         \n"
			"    MOV      r23, R7.b0                                             \n"
			"    QBGE     CHK_RX_CMPL_INT, R7.b0, r22                            \n"
			"    SUB      r23, R7.b0, r22                                        \n"
			"CHK_RX_CMPL_INT:                                                    \n"
			"    QBLT     RxInterruptServiceRequestHndlr, r22, r23               \n"
			"RX_COMPLETE:                                                        \n"
			"    CLR      R5.b2, R5.b2, 1                                        \n"
			"    QBEQ     CHK_RX_OVERRUN, R7.b0, r22                             \n"
			"    XOR      R7.b0, R7.b0, R7.b0                                    \n"
			"    SBBO     &R7.b0, R8, 12,  1                                     \n"
			"    SET      R5.b2, R5.b2, 1                                        \n"
			"CHK_RX_OVERRUN:                                                     \n"
			"    LDI      r23.w0, 0x284 & 0xFFFF                                 \n"
			"    LDI      r23.w2, 0x284 >> 16                                    \n"
			"    LBCO     &r22, C0, r23, 4                                       \n"
			"    ADD      r23, R10.b2, 2                                         \n"
			"    ADD      r23, R10.b2, 2                                         \n"
			"OVER_RUN_ERR:                                                       \n"
			"    QBBC     CHK_RX_READY_BIT, r22, r23                             \n"
			"    QBBC     CHK_RX_READY_BIT, R4.w2, 15                            \n"
			"    SET      R5.b2, R5.b2, 3                                        \n"
			"    SET      R5.b2, R5.b2, 2                                        \n"
			"CHK_RX_READY_BIT:                                                   \n"
			"    QBBC     RxInterruptServiceRequestHndlr, R5.b2, 0               \n"
			"    JMP      RX_CHN_INTR                                            \n"
			"BIT_CLEARD:                                                         \n"
			"    SET      R5.b2, R5.b2, 4                                        \n"
			"    JMP      SET_RX_ERR_STAT                                        \n"
			"RX_DATA_ZERO:                                                       \n"
			"    SET      R5.b2, R5.b2, 5                                        \n"
			"SET_RX_ERR_STAT:                                                    \n"
			"    SET      R2.w2, R2.w2, 9                                        \n"
			"    SET      R5.b2, R5.b2, 2                                        \n"
			"    QBBC     RxInterruptServiceRequestHndlr, R2.w0, 9               \n"
			"    QBBC     BREAK_COND_ERR, R5.b2, 4                               \n"
			"FRAMING_ERR:                                                        \n"
			"    QBBS     RX_CHN_INTR, R4.w2, 12                                 \n"
			"    JMP      RxInterruptServiceRequestHndlr                         \n"
			"BREAK_COND_ERR:                                                     \n"
			"    QBBC     RxInterruptServiceRequestHndlr, R4.w2, 13              \n"
			"RX_CHN_INTR:                                                        \n"
			"    SET      R2.w2, R2.w2, R10.b2                                   \n"
			"    SBBO     &R2.w2, r20, 0x082, 2                                  \n"
			"    SBBO     &R5.b2, R8, 6,  1                                      \n"
			"    QBBC     RxInterruptServiceRequestHndlr, R2.w0, R10.b2          \n"
			"    JMP      PRU_TO_HOST_INTERRUPT                                  \n"
			"LOAD_RX_CONTEXT_ADDRESS:                                            \n"
			"    QBEQ     RX_CONTEXT_CH1_ADDR, R10.b2, 1                         \n"
			"    QBEQ     RX_CONTEXT_CH3_ADDR, R10.b2, 3                         \n"
			"    QBEQ     RX_CONTEXT_CH5_ADDR, R10.b2, 5                         \n"
			"    QBEQ     RX_CONTEXT_CH7_ADDR, R10.b2, 7                         \n"
			"    jmp      r30.w0                                                 \n"
			"RX_CONTEXT_CH1_ADDR:                                                \n"
			"    LDI      R9, 0x0C0                                              \n"
			"    jmp      r30.w0                                                 \n"
			"RX_CONTEXT_CH3_ADDR:                                                \n"
			"    LDI      R9, 0x110                                              \n"
			"    jmp      r30.w0                                                 \n"
			"RX_CONTEXT_CH5_ADDR:                                                \n"
			"    LDI      R9, 0x160                                              \n"
			"    jmp      r30.w0                                                 \n"
			"RX_CONTEXT_CH7_ADDR:                                                \n"
			"    LDI      R9, 0x1B0                                              \n"
			"    jmp      r30.w0                                                 \n"
	);
}
